### ISSUE TITLE
Spice-webDAV issues running Win7 guest on Linux Mint 19.1 Host (Gnome Boxes)

### ISSUE THREAD

**Issue by tazmo8448** [lofyer/spice-webdav#3]
When I try to run/install the .man file extension given on the spice tools downloads, I receive a Window 7 error on install and the other iterations of the webDAV seem to be code and SHA check sum checks. Being unable to install the application I was wondering if there are any other options to share files using this setup. Linux Mint 19.1 Host Windows 7 Guest on Gnome Boxes.

**Comment by lofyer** [comment]
start the spice-webdav service

**Comment by tazmo8448** [comment]
I can not even run the download from Spice in Windows 7 it gives an error message saying that the .man file is not compatible.
Is there another way to run the 'spice-webdavd' service? Like in Synaptic Package or Terminal command?

**Comment by lofyer** [comment]
Using the right version?
Like x86_64 or i386.

**Comment by tazmo8448** [comment]
found out what the issue was...because I had just installed Win7 I used the native browser an in this case it was IE8 found out that the browser downloaded corrupt files...used FireFox .. and those spice links worked just fine..thanks for your time on the matter. ... 👍
